create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_length
    check (display_name is null or char_length(trim(display_name)) between 1 and 80)
);

create table public.coffee_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index coffee_logs_user_created_at_idx
  on public.coffee_logs (user_id, created_at desc, id desc);

alter table public.profiles enable row level security;
alter table public.coffee_logs enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.coffee_logs from anon, authenticated;
revoke all on sequence public.coffee_logs_id_seq from anon, authenticated;

grant select, insert, update on table public.profiles to authenticated;
grant select, insert, delete on table public.coffee_logs to authenticated;
grant usage, select on sequence public.coffee_logs_id_seq to authenticated;

create policy "Users can read their profile"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Users can create their profile"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "Users can update their profile"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Users can read their coffee logs"
  on public.coffee_logs
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can add their coffee logs"
  on public.coffee_logs
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their coffee logs"
  on public.coffee_logs
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, null)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.delete_latest_coffee()
returns setof public.coffee_logs
language sql
security invoker
set search_path = ''
as $$
  delete from public.coffee_logs
  where id = (
    select id
    from public.coffee_logs
    where user_id = (select auth.uid())
    order by created_at desc, id desc
    limit 1
  )
  returning *;
$$;

revoke all on function public.delete_latest_coffee() from public, anon;
grant execute on function public.delete_latest_coffee() to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'coffee_logs'
  ) then
    alter publication supabase_realtime add table public.coffee_logs;
  end if;
end;
$$;
